In [ ]:

#Important Methods for Sorting DataFrames
#sort_values() - Sorts the DataFrame by the values of one or more columns.
#sort_index() - Sorts the DataFrame by its index (row labels).
#nlargest(n) - Returns the n largest values in a column.
#nsmallest(n) - Returns the n smallest values in a column.

import pandas as pd
inpFilePath ='/Users/sam/git/Pandas_Data/Input/Data_2019/'
df = pd.read_csv(inpFilePath+'survey_results_public.csv')
schema_df = pd.read_csv(inpFilePath+'survey_results_schema.csv')
pd.set_option('display.max_columns', 85) #to display all columns in the dataframe
pd.set_option('display.max_rows', 85)   #to ee all rows in the dataframe of schema
pd.set_option('display.max_colwidth', 100) #to see the full description of the columns in the schema dataframe

people = {
    "first": ["Corey", "Jane", "John","Adam"],
    "last": ["Schafer", "Doe", "Doe","Doe"],
    "email": ["Corey.Schafer@gmail.com", "Jane.Doe@gmail.com", "John.Smith@gmail.com","Adam.Doe@gmail.com"]
}
df1 = pd.DataFrame(people)
df1

   first     last                    email
0  Corey  Schafer  Corey.Schafer@gmail.com
1   Jane      Doe       Jane.Doe@gmail.com
2   John      Doe     John.Smith@gmail.com
3   Adam      Doe       Adam.Doe@gmail.com

In [4]:
df1.sort_values(by='last') #if there is a tie in the last name, then it will sort by whosoever comes first in the dataframe. 
#In this case, Jane will come before John and Adam because Jane is before them in the dataframe.

   first     last                    email
1   Jane      Doe       Jane.Doe@gmail.com
2   John      Doe     John.Smith@gmail.com
3   Adam      Doe       Adam.Doe@gmail.com
0  Corey  Schafer  Corey.Schafer@gmail.com

In [5]:
df1.sort_values(by='last', ascending=False)

   first     last                    email
0  Corey  Schafer  Corey.Schafer@gmail.com
1   Jane      Doe       Jane.Doe@gmail.com
2   John      Doe     John.Smith@gmail.com
3   Adam      Doe       Adam.Doe@gmail.com

In [6]:
df1.sort_values(by=['last','first'],ascending=[False,True],inplace=True)
df1

   first     last                    email
0  Corey  Schafer  Corey.Schafer@gmail.com
3   Adam      Doe       Adam.Doe@gmail.com
1   Jane      Doe       Jane.Doe@gmail.com
2   John      Doe     John.Smith@gmail.com

In [10]:
df1.sort_index() #will sort based on row labels , here its index
#but this will not update the dataframe because we have not set inplace to True. 
# So, we will have to set inplace to True to update the dataframe.S

   first     last                    email
0  Corey  Schafer  Corey.Schafer@gmail.com
1   Jane      Doe       Jane.Doe@gmail.com
2   John      Doe     John.Smith@gmail.com
3   Adam      Doe       Adam.Doe@gmail.com

In [11]:
df1['last']

0    Schafer
3        Doe
1        Doe
2        Doe
Name: last, dtype: object

In [12]:
#we can also sort the series i.e. columns of the dataframe using sort_values() method.
df1['last'].sort_values() #will sort in ascending order by default.

3        Doe
1        Doe
2        Doe
0    Schafer
Name: last, dtype: object

In [13]:
df.head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software is about the same,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or tool without taking a formal course",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how to do things I didn’t necessarily look for,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a job board","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Industry news about technologies you're interested in;...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software is about the same,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)",NaN,Taken an online course in programming or software development (e.g. a MOOC),NaN,"Developer, desktop or enterprise applications;Developer, front-end",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the company or organization;Specific department or te...,"Something else changed (education, award, media, etc.)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change many aspects of our lives,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how to do things I didn’t necessarily look for,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board but have never used or visited it","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Industry news about technologies you're interested in;...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write code sometimes as part of my work",Yes,Never,The quality of OSS and closed source software is about the same,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or tool without taking a formal course",100 to 499 employees,"Designer;Developer, back-end;Developer, front-end;Developer, full-stack",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new opportunities",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies I'd be working with;Remote work options;Flex time ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what seems most important or urgent,Distracting work environment;Inadequate access to necessary tools;Lack of support from management,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how to do things I didn’t necessarily look for,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a private Q&A instance",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on technologies you're interested in,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software is about the same,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or software engineering",Taken an online course in programming or software development (e.g. a MOOC);Received on-the-job ...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Interview with people in senior / management roles",No,"Languages, frameworks, and other technologies I'd be working with;Office environment or company ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what seems most important or urgent,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence on purchasing new technology,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the time / relax,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Industry news about technologies you're interested in;...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than proprietary / closed source software",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or software engineering",Taken an online course in programming or software development (e.g. a MOOC);Received on-the-job ...,"10,000 or more employees","Academic researcher;Developer, desktop or enterprise applications;Developer, full-stack;Develope...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a whiteboard);Solve a brain-teaser style puzzle;Inte...",No,"Industry that I'd be working in;Languages, frameworks, and other technologies I'd be working wit...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,"There is a schedule and/or spec (made by me or by a colleague), and I follow it very closely",Being tasked with non-development work;Inadequate access to necessary tools;Non-work commitments...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board but have never used or visited it","No, I've heard of them, but I am not part of a private Q&A instance","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on technologies you're interested in,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [14]:
df.sort_values(by = ['Country','ConvertedComp'], ascending=[True , False], inplace=True)

#Since Country is sorted in ascending order so first countries with name A will come first and so on
#Since ConvertedComp is sorted in descending order, we will have the highest paid people at the top of each country first.
#so first row would whosoever earning highest in countries starting with A
#inPlace is set to True so the changes will be reflected in the original dataframe.
df[['Country','ConvertedComp']].head(50)

           Country  ConvertedComp
62723  Afghanistan      1000000.0
50172  Afghanistan       153216.0
39018  Afghanistan        19152.0
58082  Afghanistan        17556.0
7056   Afghanistan        14364.0
22327  Afghanistan         7980.0
48122  Afghanistan         4464.0
10697  Afghanistan         3996.0
8112   Afghanistan         1596.0
29560  Afghanistan         1116.0
719    Afghanistan            0.0
28470  Afghanistan            0.0
6391   Afghanistan            NaN
7323   Afghanistan            NaN
12253  Afghanistan            NaN
26189  Afghanistan            NaN
28877  Afghanistan            NaN
32971  Afghanistan            NaN
37571  Afghanistan            NaN
39754  Afghanistan            NaN
42832  Afghanistan            NaN
44123  Afghanistan            NaN
45562  Afghanistan            NaN
46807  Afghanistan            NaN
49377  Afghanistan            NaN
50437  Afghanistan            NaN
51525  Afghanistan            NaN
58390  Afghanistan            NaN
59184  Afghanistan            NaN
60185  Afghanistan            NaN
60559  Afghanistan            NaN
61770  Afghanistan            NaN
62124  Afghanistan            NaN
73920  Afghanistan            NaN
80423  Afghanistan            NaN
85185  Afghanistan            NaN
85293  Afghanistan            NaN
85827  Afghanistan            NaN
86394  Afghanistan            NaN
86551  Afghanistan            NaN
88033  Afghanistan            NaN
88181  Afghanistan            NaN
88340  Afghanistan            NaN
88735  Afghanistan            NaN
38075      Albania       187668.0
3771       Albania       114550.0
9230       Albania        74474.0
6688       Albania        60000.0
10257      Albania        57300.0
65859      Albania        41244.0

In [15]:
df

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
62723,63129,I am a developer by profession,Yes,Never,"OSS is, on average, of HIGHER quality than proprietary / closed source software",Employed full-time,Afghanistan,"Yes, full-time",I never completed any formal education,NaN,Taken an online course in programming or software development (e.g. a MOOC),"Just me - I am a freelancer, sole proprietor, etc.",NaN,Less than 1 year,Younger than 5 years,1,Very dissatisfied,Very dissatisfied,Very confident,Yes,Yes,I am actively looking for a job,I've never had a job,Write any code,Yes,How widely used or impactful my work output would be,I had a negative experience or interaction at work,AED,United Arab Emirates dirham,648838511.0,Monthly,1000000.0,168.0,"There is a schedule and/or spec (made by me or by a colleague), and I follow it very closely",Being tasked with non-development work,It's complicated,"Other place, such as a coworking space or cafe",Far below average,No,NaN,NaN,NaN,NaN,Assembly;Bash/Shell/PowerShell;Other(s):,Bash/Shell/PowerShell;TypeScript,MySQL,MySQL,Android;iOS;Windows;WordPress;Other(s):,Android;iOS;Windows;WordPress;Other(s):,Angular/Angular.js;Express;jQuery;Laravel;Other(s):,Angular/Angular.js;Express;jQuery;Laravel;Other(s):,Ansible;Apache Spark;Torch/PyTorch,Apache Spark;Torch/PyTorch,Android Studio;Atom;Coda;Eclipse;Emacs;IPython / Jupyter;Light Table;NetBeans;Notepad++;PHPStorm...,Windows,"Outside of work, for personal projects",Accepting Bitcoin or other coins and tokens as payments,Useful across many domains and could change many aspects of our lives,Yes,Yes,Yes,I don't use social media,Online,UserID,NaN,I have never visited Stack Overflow (before today),Find answers to specific questions,Less than once per week,Stack Overflow was much faster,0-10 minutes,NaN,NaN,"No, I didn't know that Stack Overflow had a job board",NaN,"No, not at all",NaN,Tech articles written by other developers,NaN,NaN,NaN,NaN,NaN,Yes,Too short,Easy
50172,50499,"I am not primarily a developer, but I write code sometimes as part of my work",Yes,Less than once per year,"OSS is, on average, of LOWER quality than proprietary / closed source software",Employed full-time,Afghanistan,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","A health science (ex. nursing, pharmacy, radiology)",Participated in a full-time developer training program or bootcamp;Taken a part-time in-person c...,"10,000 or more employees","Data or business analyst;Database administrator;Designer;Developer, back-end;Developer, desktop ...",7,27,7,Very dissatisfied,Very dissatisfied,Somewhat confident,Yes,Yes,"I’m not actively looking, but I am open to new opportunities",More than 4 years ago,"Write code by hand (e.g., on a whiteboard);Interview with people in senior / management roles",No,Opportunities for professional development;Diversity of the company or organization;How widely u...,"Something else changed (education, award, media, etc.)",AFN,Afghan afghani,960000.0,Monthly,153216.0,40.0,"There is a schedule and/or spec (made by me or by a colleague), and my work somewhat aligns",Lack of support from management;Time spent commuting;Toxic work environment,Less than once per month / Never,Office,A little above average,"Yes, because I see value in code review",8.0,"Yes, it's not part of our process but the developers do it on their own",Developers typically have the most influence on purchasing new technology,I have a great deal of influence,C#;HTML/CSS;JavaScript;SQL;VBA,C#;HTML/CSS;JavaScript;R;SQL;TypeScript;VBA,Microsoft SQL Server;PostgreSQL;SQLite,MariaDB;MongoDB;Microsoft SQL Server;PostgreSQL;SQLite,NaN,Android,ASP.NET;jQuery,Angular/Angular.js;ASP.NET;jQuery;React.js;Vue.js,.NET,.NET;.NET Core;Node.js;Xamarin,Visual Studio,Windows,I do not use containers,Implementing our own cryptocurrency,NaN,Yes,Yes,Yes,WhatsApp,Online,Login,2013,A few times per month or weekly,Find answers to specific questions,Less than once per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Industry news about technologies you're interested in;...,34.0,NaN,No,Straight / Heterosexual,NaN,Yes,Too long,Neither easy nor difficult
39018,39258,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of LOWER quality than proprietary / closed source software",Employed full-time,Afghanistan,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or software engineering",Taken an online course in programming or software development (e.g. a MOOC);Taken a part-time in...,100 to 499 employees,"Database administrator;Designer;Developer, back-end;Developer, desktop or enterprise application...",2,22,1,Very satisfied,Very satisfied,Very confident,No,Yes,"I’m not actively looking, but I am open to new opportunities",1-2 years ago,"Write code by hand (e.g., on a whiteboard);Interview with people in peer roles;Interview with pe...",No,"Languages, frameworks, and other technologies I'd be working with;Office environment or company ...","Something else changed (education, award, media, etc.)",AFN,Afghan afghani,120000.0,Monthly,19152.0,49.0,"There is a schedule and/or spec (made by me or by a colleague), and I follow it very closely",Not enough people for the workload;Time spent commuting,Less than once per month / Never,Office,Far above average,"Yes, because I see value in code review",10.0,"Yes, it's not part of our process but the developers do it on their own",Developers typically have the most influence on purchasing new technology,I have some influence,HTML/CSS;JavaScript;PHP;SQL;TypeScript,C#;Dart;JavaScript;SQL;TypeScript,MariaDB;MongoDB;MySQL;PostgreSQL,Couchbase;Firebase;MariaDB;MongoDB;Redis,Android;AWS;Linux;Windows;WordPress,Android;AWS;Docker;Heroku;iOS;Linux;Raspberry Pi;Windows;WordPress,Angular/Angular.js;Drupal;Express;Laravel,Angular/Angular.js;Drupal;Express,Cordova;Node.js,Hadoop;Node.js,Notepad++;PHPStorm;Vim;Visual Studio Code,Linux-based,Production,NaN,NaN,Yes,Yes,No,Facebook,Online,Login,2016,A few times per week,Find answers to specific questions;Learn how to do things I didn’t necessarily look for;Get a se...,1-2 times per week,Stack Overflow was much faster,0-10 minutes,Yes,Less than once per month or monthly,Yes,NaN,"Yes, somewhat",NaN,Tech articles written by other developers;Industry news about technologies you're interested in;...,26.0,Man,No,Straight / Heterosexual,East Asian;South Asian,Yes,Too long,Easy
58082,58450,I am a developer by profession,Yes,Never,"OSS is, on average, of HIGHER quality than proprietary / closed source software",Employed full-time,Afghanistan,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or software engineering",Taken an online course in programming or software development (e.g. a MOOC);Participated in a fu...,"10,000 or more employees","Developer, back-end;Developer, desktop or enterprise applications;Developer, front-end;Developer...",6,20,2,Neither satisfied nor dissatisfied,Slightly satisfied,Very confident,Yes,Yes,I am actively looking for a job,1-2 years ago,"Write code by hand (e.g., on a whiteboard);Complete a take-home project;Interview with people in...",No,"Languages, frameworks, and other technologies I'd be working with;Office environment or company ...",I had a negative experience or interaction at work,AFN,Afghan afghani,110000.0,Monthly,17556.0,40.0,"There is a schedule and/or spec (made by me or by a colleague), and I follow it very closely",Distracting work environment,It's complicated,Office,Average,"Yes, because I see value in code review",8.0,"Yes, it's part of our process",Developers typically have the most influence on purchasing new technology,I have little or no influence,Assembly;C;C++;HTML/CSS;Java;PHP;SQL,C;C++;HTML/CSS;Java;JavaScript;SQL;TypeScript,MySQL;PostgreSQL,MySQL;PostgreSQL,Linux;Windows,Windows,NaN,Spring,NaN,Node.js,IntelliJ;Notepad++,Windows,Development,Accepting Bitcoin or other coins and tokens as payments,Useful for immutable record keeping outside of currency,Yes,Yes,Yes,Facebook,Online,Handle,NaN,Daily or almost daily,Find answers to specific questions;Learn how to do things I didn’t necessarily look for;Contribu...,6-10 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I didn't know that Stack Overflow had a job board","No, and I don't know what those are","Yes, definitely",A lot less welcome now than last year,Tech articles written by other developers,26.0,Man,No,Straight / Heterosexual,South Asian,No,Too long,Neither easy nor difficult
7056,7085,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software is about the same,"Independent contractor, freelancer, or self-employed",Afghanistan,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or software engineering","Taught yourself a new language, framework, or tool without taking a formal course",2-9 employees,"Developer, full-stack",7,19,6,Slightly dissatisfied,Neither satisfied nor dissatisfied,NaN,NaN,NaN,"I’m not actively looking, but I am open to new opportunities",Less than a year ago,Interview with people in peer roles;Interview with people in senior / management roles,No,"Languages, frameworks, and other technologies I'd be working with;Office environment or company ...",I was preparing for a job search,AFN,Afghan afghani,90000.0,Monthly,14364.0,30.0,There's no schedule or spec; I work on what seems most important or urgent,Inadequate access to necessary tools;Lack of support from management;Toxic work environment,About half the time,Office,Average,"Yes, because I see value in code review",3.0,NaN,NaN,NaN,HTML/CSS;JavaScript;PHP,JavaScript;Kotlin;PHP,MySQL,MongoDB;MySQL;Redis,Linux;MacOS;Other(s):,Linux;MacOS;Other(s):,jQuery;Laravel;Vue.js,ASP.NET;jQuery;Laravel;Vue.js,NaN,React Native,Sublime Text;Visual Studio Code,MacOS,"Development;Outside of work, for personal projects",NaN,NaN,Yes,Also Yes,Yes,Instagram,Online,UserID,2016,Multiple times per day,Find answers to specific questions;Learn how to do things I didn’t necessarily look for,6-10 times per week,Stack Overflow was much faster,60+ minutes,Yes,A few times per week,"No, I knew that Stack Overflow had a job board but have never used or visited it","No, I've heard of them, but I am not part of a private Q&A instance","Yes, somewhat",Just as welcome now as I felt last year,Industry news about technologies you're interested in;Tech meetups or events in your area,26.0,Man,NaN,Straight / Heterosexual,East Asian,Yes,Appropriate in length,Neither easy nor difficult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88873,88062,NaN,No,Never,"OSS is, on average, of LOWER quality than proprietary / closed source software",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88874,88076,NaN,No,Never,"OSS is, on average, of HIGHER quality than proprietary / closed source software",Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88879,88601,NaN,No,Never,The quality of OSS and closed source software is about the same,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88880,88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than proprietary / closed source software","Independent contractor, freelancer, or self-employed",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df['ConvertedComp'].nlargest(10) #for all the values in the column ConvertedComp, it will return the 10 largest values. of convertedComp.

25833    2000000.0
87353    2000000.0
21895    2000000.0
28080    2000000.0
72274    2000000.0
77665    2000000.0
79701    2000000.0
51798    2000000.0
75088    2000000.0
32056    2000000.0
Name: ConvertedComp, dtype: float64

In [18]:
df.nlargest(10,'ConvertedComp') 
#if we want to see the other columns as well for those 10 largest values of ConvertedComp, then we can use nlargest() method on the dataframe itself and pass the column name as an argument.

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
25833,25983,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than proprietary / closed source software",Employed full-time,Canada,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or software engineering","Received on-the-job training in software development;Taught yourself a new language, framework, ...","10,000 or more employees","Developer, full-stack",8,16,2,Very satisfied,Very satisfied,Somewhat confident,No,No,"I’m not actively looking, but I am open to new opportunities",3-4 years ago,Solve a brain-teaser style puzzle;Interview with people in senior / management roles,No,Remote work options;Opportunities for professional development;Flex time or a flexible schedule,"My job status changed (promotion, new job, etc.)",USD,United States dollar,65500.0,Weekly,2000000.0,45.0,"There is a schedule and/or spec (made by me or by a colleague), and I follow it very closely",Being tasked with non-development work;Meetings;Not enough people for the workload,A few days each month,Office,Average,"Yes, because I see value in code review",2.0,"Yes, it's part of our process",Developers and management have nearly equal input into purchasing new technology,I have little or no influence,Bash/Shell/PowerShell;C++;C#;HTML/CSS;JavaScript;Python;SQL;TypeScript,Bash/Shell/PowerShell;C#;F#;Python;SQL;TypeScript,Microsoft SQL Server;MySQL,Microsoft SQL Server;MySQL,AWS;Docker;Heroku;Linux;MacOS;Raspberry Pi;Windows,AWS;Docker;Linux;MacOS;Windows,Angular/Angular.js,Angular/Angular.js;Flask;React.js,.NET;.NET Core;Node.js,.NET Core;Node.js,Notepad++;Sublime Text;Vim;Visual Studio;Visual Studio Code,Windows,Development;Production,NaN,"Useful for decentralized currency (i.e., Bitcoin)",No,Yes,Yes,Reddit,In real life (in person),Username,2013,Daily or almost daily,Find answers to specific questions;Learn how to do things I didn’t necessarily look for,1-2 times per week,Stack Overflow was much faster,11-30 minutes,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board but have never used or visited it","No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,NaN,24.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
87353,87896,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software is about the same,Employed full-time,Germany,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or software engineering",Taken an online course in programming or software development (e.g. a MOOC);Completed an industr...,2-9 employees,"Developer, full-stack",9,17,8,Very satisfied,Very satisfied,Somewhat confident,No,I am already a manager,I am not interested in new job opportunities,More than 4 years ago,Write any code;Interview with people in senior / management roles,No,Office environment or company culture;Diversity of the company or organization;Flex time or a fl...,"Something else changed (education, award, media, etc.)",USD,United States dollar,55000.0,Weekly,2000000.0,40.0,"There is a schedule and/or spec (made by me or by a colleague), and my work somewhat aligns",Being tasked with non-development work;Meetings;Not enough people for the workload,All or almost all the time (I'm full-time remote),Home,A little above average,"Yes, because I see value in code review",3.0,"No, but I think we should",Developers and management have nearly equal input into purchasing new technology,I have a great deal of influence,HTML/CSS;JavaScript;PHP;SQL,HTML/CSS;JavaScript;PHP;Ruby;SQL;TypeScript,MariaDB;MySQL;PostgreSQL,MariaDB;MySQL;PostgreSQL,WordPress,NaN,jQuery;Laravel;Vue.js,Express;Laravel;Ruby on Rails;Vue.js,NaN,Node.js,Sublime Text;Vim;Visual Studio Code,Linux-based,I do not use containers,Not at all,Useful for immutable record keeping outside of currency,No,Yes,Yes,Twitter,Online,Handle,2011,Daily or almost daily,Find answers to specific questions,3-5 times per week,Stack Overflow was much faster,0-10 minutes,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board but have never used or visited it","No, I've heard of them, but I am not part of a private Q&A instance","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Tech meetups or events in your area,32.0,Man,No,Gay or Lesbian,White or of European descent,No,Appropriate in length,Neither easy nor difficult
21895,22013,I am a developer by profession,Yes,Never,The quality of OSS and closed source software is about the same,Employed full-time,India,No,"Professional degree (JD, MD, etc.)","A natural science (ex. biology, chemistry, physics)",Taken an online course in programming or software development (e.g. a MOOC);Participated in a fu...,2-9 employees,"Academic researcher;Data scientist or machine learning specialist;Designer;Developer, game or gr...",3,26,3,Very satisfied,Very satisfied,NaN,NaN,NaN,I am not interested in new job opportunities,3-4 years ago,"Write code by hand (e.g., on a whiteboard);Complete a take-home project;Solve a brain-teaser sty...",No,"Financial performance or funding status of the company or organization;Languages, frameworks, an...","Something else changed (education, award, media, etc.)",USD,United States dollar,1500000.0,Weekly,2000000.0,50.0,There's no schedule or spec; I work on what seems most important or urgent,Inadequate access to necessary tools;Meetings;Not enough people for the workload,All or almost all the time (I'm full-time remote),Home,A little below average,"Yes, because I see value in code review",10.0,"Yes, it's part of our process",Developers typically have the most influence on purchasing new technology,I have a great deal of influence,Assembly;Bash/Shell/PowerShell;C;C++;Java;JavaScript;Python;SQL;Other(s):,Python;Swift,Cassandra;Microsoft SQL Server;Oracle,Cassandra,Android;Arduino;Google Cloud Platform;IBM Cloud or Watson;Windows,IBM Cloud or Watson;Windows,jQuery,NaN,TensorFlow,TensorFlow,Visual Studio;Visual Studio Code,Windows,Development,Implementing our own cryptocurrency,Useful across many domains and could change many aspects of our lives,Yes,Yes,No,YouTube,Online,Screen Name,NaN,A few times per week,Find answers to specific questions,1-2 times per week,Stack Overflow was much faster,60+ minutes,Yes,I have never participated in Q&A on Stack Overflow,Yes,Yes,"Yes, definitely",A lot more welcome now than last year,Tech articles written by other developers;Industry news about technologies you're interested in;...,NaN,Man,No,Straight / Heterosexual,NaN,Yes,Too long,Easy
28080,28243,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than proprietary / closed source software","Independent contractor, freelancer, or self-employed",India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or software engineering",Taken an online course in programming or software development (e.g. a MOOC);Completed an industr...,2-9 employees,"Developer, back-end;Developer, full-stack;Developer, game or graphics;Developer, mobile",25,9,14,Neither satisfied nor dissatisfied,Neither satisfied nor dissatisfied,NaN,NaN,NaN,"I’m not actively looking, but I am open to new opportunities",1-2 years ago,Interview with people in peer roles;Interview with people in senior / management roles,Yes,Financial performance or funding status of the company or organization;Specific department or te...,"I heard about a job opportunity (from a recruiter, online job posting, etc.)",USD,United States dollar,2000000.0,Yearly,2000000.0,20.0,"There is a schedule and/or spec (made by me or by a colleague), and I follow it very closely",Being tasked with non-development work;Not enough people for the workload;Time spent commuting,All or almost all the time (I'm full-time remote),Office,Far above average,"Yes, because I see value in code review",NaN,NaN,NaN,NaN,C++;C#;Java;JavaScript;Objective-C;Python,C;C++;C#,PostgreSQL;SQLite,SQLite,Android;AWS;iOS;MacOS;Windows,Android;Linux,NaN,NaN,Node.js;Pandas;Unity 3D,Unity 3D;Unreal Engine,Android Studio;Coda;PyCharm;Visual Studio;Visual Studio Code;Xcode,MacOS,I do not use containers,NaN,An irresponsible use of resources,No,Yes,No,I don't use social media,In real life (in person),Username,2008,Daily or almost daily,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,60+ minutes,Yes,Multiple times per day,Yes,"No, and I don't know what those are","Yes, definitely",A lot less welcome now than last year,Tech meetups or events in your area,NaN,NaN,NaN,Straight / Heterosexual,NaN,Yes,Too short,Easy
72274,72732,"I am not primarily a developer, but I write code sometimes as part of my work",No,Less than once a month but more than once per year,"OSS is, on average, of LOWER quality than proprietary / closed source software",NaN,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or software engineering",Contributed to open source software,NaN,NaN,4,20,5,Slightly satisfied,Slightly satisfied,NaN,NaN,NaN,I am actively looking for a job,More than 4 years ago,Write any code,No,Remote work options;Opportunities for professional development;Flex time or a flexible schedule,I was preparing for a job search,USD,United States dollar,80000.0,Weekly,2000000.0,40.0,"There is a schedule and/or spec (made by me or by a colleague), and I follow it very closely",Lack of support from management;Meetings;Time spent commuting,Less than once per month / Never,Office,A little above average,"Yes, because I see value in code review",10.0,"Yes, it's part of our process",Not sure,I have little or no influence,Java;Python;SQL,NaN,MongoDB;Microsoft SQL Server;MySQL;Oracle;PostgreSQL,MySQL,Android;Windows,AWS;Docker,NaN,Angular/Angular.js;React.js,NaN,NaN,Eclipse;Notepad++;PyCharm,Windows,Testing,NaN,NaN,Yes,Yes,No,WhatsApp,Neither,NaN,2017,A few times per month or weekly,Get a sense of belonging to the developer community,1-2 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,A few times per month or weekly,Yes,"No, and I don't know what those are",Not sure,A lot less welcome now than last year,Tech articles written by other developers;Tech meetups or events in your area;Courses on technol...,NaN,Man,No,NaN,NaN,Yes,Too long,Easy
77665,78151,I am a developer by profession,Yes,Never,"OSS is, on average, of HIGHER quality than proprietary / closed source software",Employed full-time,Mexico,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or software engineering",Taken an online course in programming or software development (e.g. a MOOC);Received on-the-job ...,100 to 499 employees,"Developer, full-stack",15,18,10,Very satisfied,Very satisfied,Somewhat confident,No,Yes,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Interview with people in senior / management roles",Yes,"Languages, frameworks, and other technologies I'd be working with;Office environment or company ...","My job status changed (promotion, new job, etc.)",USD,United States dollar,95000.0,Weekly,2000000.0,30.0,"There is a schedule and/or spec (made by me or by a colleague), and my work somewhat aligns",Being tasked with non-development work;Distracting work environment;Meetings,Less than once per month / Never,Office,A little above average,No,NaN,"No, but I think we should","The CTO, CIO, or other management purchase new technology typically without the involvement of d...",I have little or no influence,C#;HTML/CSS;JavaScript;SQL;TypeScript,C#;TypeScript;WebAssembly,Microsoft SQL Server,Microsoft SQL Server,Windows,Android;Arduino;Raspberry Pi,Angular/Angular.js;ASP.NET;jQuery;Vue.js,Angular/Angular.js;Vue.js,.NET,.NET Core;Xamarin,Visual Studio,Windows,I do not use containers,Non-currency applications of blockchain,Useful for immutable record keeping outside of currency,Yes,Yes,Yes,Reddit,In real life (in person),Username,2010,Multiple times per day,Learn how to do things I didn’t necessarily look for;Contribute to a library of information;Pass...,1-2 times per week,Stack Overflow was much faster,60+ minutes,Yes,A few times per month or weekly,Yes,"No, I've heard of them, but I am not part of a private Q&A instance",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on technologies you're interested in,32.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina,No,Appropriate in length,Easy
79701,80200,I am a developer by profession,Yes,Never,"OSS is, on average, of LOWER quality than proprietary / closed source software",Employed full-time,Netherlands,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or software engineering","Received on-the-job training in software development;Taught yourself a new language, framework, ...","1,000 to 4,999 employees","Developer, front-end;Developer, mobile",8,17,4,Very satisfied,Very satisfied,Somewhat confident,Yes,Yes,I am not interested in new job opportunities,More than 4 years ago,Complete a take-home project;Interview with people in peer roles;Interview with people in senior...,No,Office environment or company culture;Diversity of the company or organization;How widely used o...,"My job status changed (promotion, new job, etc.)",USD,United States dollar,120000.0,Weekly,2000000.0,45.0,"There is a schedule and/or spec (made by me or by a colleague), and I follow it very closely",Distracting work environment,A few days each month,Office,Average,"Yes, because I see value in code review",15.0,"Yes, it's not part of our process but the developers do it on their own",Not sure,I have little or no influence,Objective-C;Swift,Swift,NaN,NaN,Arduino;iOS;MacOS,Arduino;iOS;MacOS;Slack,NaN,NaN,NaN,NaN,Sublime Text;Vim;Xcode,MacOS,I do not use containers,Not at all,Useful for immutable record keeping outside of currency,Yes,SIGH,Yes,Instagram,In real life (in person),Handle,2011,Multiple times per day,Find answers to specific questions,1-2 times per week,Stack Overflow was slightly faster,NaN,No,NaN,"No, I knew that Stack Overflow had a job board but have never used or visited it","No, and I don't know what those are",Neutral,NaN,Tech articles written by other developers,25.0,Woman,No,Bisexual,White or of European descent,No,Appropriate in length,Easy
51798,52132,I am a developer by profession,Yes,Less than once a month but more than once per year,"OSS is, on average, of HIGHER quality than proprietary / closed source software",Employed full-time,Peru,No,Some college/university study without earning a degree,I never declared a major,"Completed an industry certification program (e.g. MCPD);Taught yourself a new language, framewor...",100 to 499 employees,"Database administrator;Developer, back-end;Developer, desktop or enterprise applications;Develop...",26,15,24,Slightly satisfied,Slightly dissatisfied,Not at all confident,No,I am already a manager,I am not interested in new job opportunities,3-4 years ago,Write any code;Interview with people in peer roles;Interview with people in senior / management ...,No,"Languages, frameworks, and other technologies I'd be working with;Remote work options;Flex time ...",I was preparing for a job search,USD,United States dollar,75000.0,Weekly,2000000.0,55.0,"There is a schedule and/or spec (made by me or by a colleague), and my work somewhat aligns",Distracting work environment;Meetings,All or almost all the time (I'm full-time remote),Home,Far above average,"Yes, because I see value in code review",6.0,"Yes, it's not part of our process but the developers do it on their own",Developers typically have the most influence on purchasing new technology,I have a great deal of influence,C++;HTML/CSS;JavaScript;Python;SQL;TypeScript,C++;HTML/CSS;JavaScript;Rust;SQL;TypeScript;WebAssembly,Firebase;PostgreSQL,Firebase;PostgreSQL,Android;AWS;Docker;Linux;Microsoft Azure;Slack;Windows,Android;Arduino;Kubernetes;Linux;Raspberry Pi,Express,Express,Ansible;Cordova;Node.js,Ansible;Cordova;Node.js,Vim;Visual Studio Code,Linux-based,Development;Testing;Production,Not at all,A passing fad,No,SIGH,What?,WhatsApp,Neither,Username,2008,A few times per week,Find answers to specific questions,1-2 times per week,Stack Overflow was much faster,11-30 minutes,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board but have never used or visited it","No, I've heard of them, but I am not part of a private Q&A instance","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Tech meetups or events in your area,48.0,Man,NaN,NaN,"Black or of African descent;East Asian;Hispanic or Latino/Latina;Middle Eastern;Native American,...",Yes,Appropriate in length,Easy

In [17]:
df.nsmallest(10,'ConvertedComp') #for all the values in the column ConvertedComp, it will return the 10 smallest values.

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
719,722,I am a developer by profession,No,Less than once a month but more than once per year,The quality of OSS and closed source software is about the same,NaN,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,Less than 1 year,Younger than 5 years,Less than 1 year,Very satisfied,Very satisfied,NaN,NaN,NaN,I am not interested in new job opportunities,NA - I am an independent contractor or self employed,NaN,No,NaN,"I heard about a job opportunity (from a recruiter, online job posting, etc.)",AFN,Afghan afghani,1.0,Yearly,0.0,1.0,NaN,NaN,Less than once per month / Never,"Other place, such as a coworking space or cafe",Far above average,"Yes, because I see value in code review",1.0,"No, and I'm glad we don't",NaN,I have little or no influence,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,SIGH,What?,NaN,Neither,NaN,2008,Multiple times per day,NaN,More than 10 times per week,The other resource was much faster,60+ minutes,Not sure / can't remember,NaN,Yes,Yes,Not sure,Not applicable - I did not use Stack Overflow last year,NaN,1.0,NaN,NaN,NaN,NaN,NaN,Too long,Difficult
28470,28638,I am a developer by profession,Yes,Less than once a month but more than once per year,"OSS is, on average, of HIGHER quality than proprietary / closed source software","Independent contractor, freelancer, or self-employed",Afghanistan,NaN,"Other doctoral degree (Ph.D, Ed.D., etc.)",I never declared a major,NaN,NaN,NaN,36,13,16,Very dissatisfied,Very dissatisfied,NaN,NaN,NaN,I am not interested in new job opportunities,NaN,NaN,NaN,NaN,NaN,AFN,Afghan afghani,3.0,Monthly,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;C;C++;Java;Objective-C;Other(s):,Bash/Shell/PowerShell;C;C++;Java;Objective-C;Other(s):,MySQL;SQLite,MySQL;SQLite,Android;iOS;Linux;MacOS,Android;iOS;Linux,jQuery,NaN,TensorFlow;Unity 3D,Hadoop;TensorFlow;Unity 3D,Emacs,Linux-based,I do not use containers,NaN,Useful for immutable record keeping outside of currency,No,Yes,No,NaN,In real life (in person),Username,2008,Daily or almost daily,Find answers to specific questions,6-10 times per week,The other resource was much faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a private Q&A instance","No, not at all",A lot less welcome now than last year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,NaN
13760,13825,I am a developer by profession,Yes,Never,The quality of OSS and closed source software is about the same,NaN,Algeria,NaN,NaN,NaN,NaN,NaN,NaN,13,83,Less than 1 year,Very dissatisfied,Very satisfied,NaN,NaN,NaN,I am actively looking for a job,NA - I am an independent contractor or self employed,Complete a take-home project;Solve a brain-teaser style puzzle;Interview with people in peer rol...,Yes,Financial performance or funding status of the company or organization;Diversity of the company ...,"Something else changed (education, award, media, etc.)",AFN,Afghan afghani,1.0,Yearly,0.0,168.0,NaN,"Being tasked with non-development work;Non-work commitments (parenting, school work, hobbies, et...",About half the time,Home,Far above average,No,NaN,"Yes, it's part of our process",NaN,I have a great deal of influence,Other(s):,Other(s):,Other(s):,Other(s):,Other(s):,Other(s):,Other(s):,Other(s):,Other(s):,Other(s):,NaN,NaN,I do not use containers,NaN,An irresponsible use of resources,No,Yes,Yes,NaN,Neither,NaN,2015,A few times per month or weekly,Find answers to specific questions,1-2 times per week,They were about the same,NaN,Yes,I have never participated in Q&A on Stack Overflow,"No, I knew that Stack Overflow had a job board but have never used or visited it","No, and I don't know what those are","No, not at all",A lot less welcome now than last year,NaN,56.0,NaN,NaN,NaN,NaN,Yes,Too short,Easy
40655,40913,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software is about the same,Employed full-time,Armenia,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or software engineering","Taught yourself a new language, framework, or tool without taking a formal course;Participated i...",2-9 employees,"Developer, desktop or enterprise applications;Developer, embedded applications or devices",7,15,4,Slightly satisfied,Slightly satisfied,Very confident,Not sure,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a whiteboard);Solve a brain-teaser style puzzle;Inte...",No,"Industry that I'd be working in;Languages, frameworks, and other technologies I'd be working wit...","Something else changed (education, award, media, etc.)",AMD,Armenian dram,0.0,Monthly,0.0,40.0,There's no schedule or spec; I work on what seems most important or urgent,"Meetings;Non-work commitments (parenting, school work, hobbies, etc.);Not enough people for the ...","Less than half the time, but at least one day each week",Office,A little above average,"Yes, because I see value in code review",3.0,"No, and I'm glad we don't",Developers and management have nearly equal input into purchasing new technology,I have a great deal of influence,Bash/Shell/PowerShell;C;C++;Java;JavaScript;Python;SQL;TypeScript,C;C++;Java;Python;SQL;TypeScript,Elasticsearch;MariaDB;MongoDB;MySQL;Redis,MariaDB;MongoDB;MySQL,Arduino;AWS;Docker;Linux;MacOS;Raspberry Pi;Slack;Windows,Arduino;Linux;MacOS;Raspberry Pi,ASP.NET;Django;Flask,Django;Flask,.NET;Node.js;TensorFlow;Torch/PyTorch,Node.js,IntelliJ;IPython / Jupyter;Sublime Text;Vim,Linux-based,Production,Not at all,A passing fad,No,SIGH,Yes,Facebook,In real life (in person),Username,2013,Multiple times per day,Find answers to specific questions;Learn how to do things I didn’t necessarily look for,3-5 times per week,Stack Overflow was much faster,0-10 minutes,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board but have never used or visited it","No, I've heard of them, but I am not part of a private Q&A instance","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers,22.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Easy
30447,30630,I am a developer by profession,Yes,Less than once a month but more than once per year,The quality of OSS and closed source software is about the same,Employed full-time,Australia,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,Taken an online course in programming or software development (e.g. a MOOC);Participated in a fu...,2-9 employees,"Database administrator;Developer, back-end;Developer, front-end;Developer, full-stack;Developer,...",35,7,30,Neither satisfied nor dissatisfied,Very satisfied,NaN,NaN,NaN,I am not interested in new job opportunities,NA - I am an independent contractor or self employed,Interview with people in peer roles;Interview with people in senior / management roles,No,Industry that I'd be working in;Office environment or company culture;How widely used or impactf...,"I heard about a job opportunity (from a recruiter, online job posting, etc.)",AUD,Australian dollar,0.0,Yearly,0.0,80.0,There's no schedule or spec; I work on what seems most important or urgent,"Distracting work environment;Non-work commitments (parenting, school work, hobbies, etc.)",It's complicated,"Other place, such as a coworking space or cafe",A little above average,"Yes, because I see value in code review",10.0,"No, but I think we should",NaN,I have a great deal of influence,Bash/Shell/PowerShell;HTML/CSS;JavaScript;Ruby,Elixir;Ruby;TypeScript,PostgreSQL,PostgreSQL,AWS;iOS,Android;AWS;iOS,Ruby on Rails;Vue.js,Ruby on Rails;Vue.js,Chef;React Native,React Native,Sublime Text;TextMate;Vim;Xcode,MacOS,I do not use containers,Not at all,An irresponsible use of resources,Yes,"Fortunately, someone else has that title",No,Reddit,Online,Username,I don't remember,A few times per month or weekly,Find answers to specific questions,1-2 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board but have never used or visited it","No, and I don't know what those are","No, not really",A lot less welcome now than last year,NaN,43.0,NaN,No,NaN,NaN,No,Appropriate in length,Easy
68611,69049,I am a developer by profession,No,Never,The quality of OSS and closed source software is about the same,"Independent contractor, freelancer, or self-employed",Australia,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or software engineering","Received on-the-job training in software development;Taught yourself a new language, framework, ...",2-9 employees,"Developer, full-stack;Engineering manager",17,12,14,Slightly satisfied,Slightly satisfied,NaN,NaN,NaN,"I’m not actively looking, but I am open to new opportunities",1-2 years ago,"Write any code;Write code by hand (e.g., on a whiteboard);Interview with people in peer roles;In...",No,Specific department or team I'd be working on;Office environment or company culture;Remote work ...,"My job status changed (promotion, new job, etc.)",AUD,Australian dollar,0.0,Yearly,0.0,25.0,"There is a schedule and/or spec (made by me or by a colleague), and my work somewhat aligns",Lack of support from management;Time spent commuting;Toxic work environment,All or almost all the time (I'm full-time remote),Home,A little above average,"Yes, because I see value in code review",1.0,NaN,NaN,NaN,Bash/Shell/PowerShell;C;C#;Go;HTML/CSS;JavaScript;Objective-C;Ruby;SQL,Dart;Elixir;JavaScript;Kotlin;Python;R;Ruby;Rust,PostgreSQL;SQLite,Cassandra;PostgreSQL;Redis,Android;Arduino;Google Cloud Platform;iOS;Linux;MacOS;Slack;Windows,Google Cloud Platform;Heroku;Kubernetes;Linux;MacOS;Slack,Ruby on Rails,Ruby on Rails;Vue.js,.NET;React Native,Ansible;Flutter;Hadoop;Pandas;React Native,IntelliJ;Visual Studio;Visual Studio Code;Xcode,MacOS,Production,NaN,A passing fad,No,Also Yes,Yes,Reddit,In real life (in person),Username,2008,A few times per week,Find answers to specific questions,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Not sure / can't remember,NaN,"No, I knew that Stack Overflow had a job board but have never used or visited it","No, I've heard of them, but I am not part of a private Q&A instance","No, not at all",Just as welcome now as I felt last year,NaN,34.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
19235,19340,"I am not primarily a developer, but I write code sometimes as part of my work",Yes,Less than once a month but more than once per year,"OSS is, on average, of HIGHER quality than proprietary / closed source software",NaN,Austria,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Fine arts or performing arts (ex. graphic design, music, studio art)",Taken an online course in programming or software development (e.g. a MOOC);Received on-the-job ...,NaN,NaN,10,20,5,Neither satisfied nor dissatisfied,Slightly satisfied,NaN,NaN,NaN,"I’m not actively looking, but I am open to new opportunities",3-4 years ago,Interview with people in peer roles;Interview with people in senior / management roles,No,Office environment or company culture;Opportunities for professional development;Flex time or a ...,I was preparing for a job search,CHF,Swiss franc,0.0,Monthly,0.0,35.0,"There is a schedule and/or spec (made by me or by a colleague), and my work somewhat aligns",Being tasked with non-development work;Inadequate access to necessary tools;Non-work commitments...,A few days each month,Office,Average,"Yes, because I see value in code review",5.0,"Yes, it's part of our process",Developers and management have nearly equal input into purchasing new technology,I have a great deal of influence,Assembly;C;Elixir;HTML/CSS;Java;JavaScript;Python;Rust;SQL,Clojure,PostgreSQL;SQLite,NaN,Arduino;Raspberry Pi,Arduino;Raspberry Pi,Other(s):,Other(s):,NaN,NaN,IntelliJ;Sublime Text,Linux-based,"Development;Testing;Production;Outside of work, for personal projects",NaN,Useful for immutable record keeping outside of currency,No,Also Yes,Yes,NaN,In real life (in person),Username,2010,A few times per week,Find answers to specific questions;Learn how to do things I didn’t necessarily look for;Meet oth...,1-2 times per week,They were about the same,NaN,Yes,I have never participated in Q&A on Stack Overflow,Yes,"No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,NaN,32.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
16126,16214,"I am not primarily a developer, but I write code sometimes as part of my work",Yes,Less than once per year,"OSS is, on average, of HIGHER quality than proprietary / closed source software",Employed full-time,Bangladesh,"Yes, part-time","Master’s degree (MA, MS, M.Eng., MBA, etc.)","A natural science (ex. biology, chemistry, physics)",NaN,20 to 99 employees,"Engineer, data;Engineering manager;Product manager;System administrator",20,16,20,Slightly satisfied,Slightly satisfied,NaN,NaN,NaN,I am not interested in new job opportunities,3-4 years ago,Interview with people in peer roles,No,Financial performance or funding status of the company or organization;Office environment or com...,I was preparing for a job search,EUR,European Euro,0.0,Yearly,0.0,10.0,There's no schedule or spec; I work on what seems most important or urgent,Lack of support from management;Meetings;Time spent commuting,Less than once per month / Never,"Other place, such as a coworking space or cafe",Far above average,No,NaN,"No, and I'm glad we don't",Developers and management have nearly equal input into purchasing new technology,I have a great deal of influence,Java;PHP;Other(s):,Java;PHP;Other(s):,MariaDB;MySQL,MariaDB;MySQL,Android;Linux;Raspberry Pi;Windows;WordPress,Android;Linux;Raspberry Pi;Windows;WordPress,jQuery;Spring,jQuery;Spring,NaN,NaN,Android Studio;Eclipse;IntelliJ;NetBeans,Linux-based,I do not use containers,Not at all,NaN,No,Yes,What?,WhatsApp,Neither,NaN,2008,Daily or almost daily,Find answers to specific questions;Contribute to a library of information,3-5 times per week,They were about the same,NaN,Yes,A few times per month or weekly,Yes,"No, I've heard of them, but I am not part of a private Q&A instance",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Courses on technologies you're interested in,99.0,NaN,No,NaN,NaN,NaN,Too long,Easy
29184,29355,I am a developer by profession,Yes,Never,"OSS is, on average, of LOWER quality than proprietary / closed source software","Independent contractor, freelancer, or self-employed",Bosnia and Herzegovina,"Yes, part-time",Some college/university study without earning a degree,"Computer science, computer engineering, or software engineering","Taught yourself a new language, framework, or tool without taking a formal course;Participated i...","Just me - I am a freelancer, sole proprietor, etc.",NaN,10,10,6,Neither satisfied nor dissatisfied,Neither satisfied nor dissatisfied,NaN,NaN,NaN,I am not interested in new job opportunities,Less than a year ago,Interview with people in senior / management roles,No,"Industry that I'd be working in;Specific department or team I'd be working on;Languages, framewo...","Something else changed (education, award, media, etc.)",BAM,Bosnia and Herzegovina convertible mark,0.0,Yearly,0.0,80.0,There's no schedule or spec; I work on what seems most important or urgent,Being tasked with non-development work;Inadequate access to necessary tools;Non-work commitments...,It's complicated,"Other place, such as a coworking space or cafe",Far above average,"Yes, because I see value in code review",20.0,NaN,NaN,NaN,Bash/Shell/PowerShell;C;C++;Python;Ruby;Other(s):,Assembly;Bash/Shell/PowerShell;C;C++;C#;Go;Other(s):,NaN,NaN,Linux;MacOS;Microsoft Azure;Raspberry Pi;Windows,Android;Arduino;AWS;iOS;Linux;MacOS;Raspberry Pi;Windows,NaN,NaN,Pandas;TensorFlow;Torch/PyTorch;Unity 3D;Unreal Engine;Xamarin,.NET;Torch/PyTorch;Unity 3D,Android Studio;Emacs;PyCharm;Visual Studio;Visual Studio Code,Linux-based,I do not use containers,NaN,A passing fad,Yes,Also Yes,Yes,YouTube,In real life (in person),Username,2013,A few times per month or weekly,Find answers to specific questions;Learn how to do things I didn’t necessarily look for;Pass the...,Less than once per week,They were about the same,NaN,Not sure / can't remember,NaN,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Industry news about technologies you're interested in,22.0,NaN,No,NaN,NaN,NaN,Too long,Easy
1678,1685,I am a developer by profession,Yes,Less than once a month but more than once per year,The quality of OSS and closed source software is about the same,"Independent contractor, freelancer, or self-employed",Brazil,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or software engineering",Taken an online course in programming or software development (e.g. a MOOC);Taught yourself a ne...,"Just me - I am a freelancer, sole proprietor, etc.","Designer;Developer, full-stack;Developer, game or graphics;Developer, mobile",8,16,3,Neither satisfied nor dissatisfied,Neither satisfied nor dissatisfied,NaN,NaN,NaN,"I’m not actively looking, but I am open to new opportunities",Less than a year ago,Interview with people in peer roles;Interview with people in senior / management roles,No,Specific department or team I'd be working on;Office environment or company culture;Opportunitie...,I was preparing for a job search,BRL,Brazilian real,0.0,Monthly,0.0,40.0,"There is a schedule and/or spec (made by me or by a colleague), and my work somewhat aligns",Distracting work environment;Meetings;Toxic work environment,All or almost all the time (I'm full-time remote),Home,Average,"Yes, because I see value in code review",6.0,NaN,NaN,NaN,Elixir;HTML/CSS;JavaScript;PHP;Python,C#;Kotlin;Python,Cassandra;MariaDB;MongoDB;PostgreSQL,Cassandra;MariaDB;MongoDB;PostgreSQL,Docker;Kubernetes;MacOS,Android;Linux;Windows,Laravel,Django;Flask;Laravel;Vue.js,Node.js,.NET;Node.js;Unity 3D;Other(s):,Android Studio;PHPStorm;PyCharm;Visual Studio Code,Windows,Development,NaN,Useful across many domains and could change many aspects of our lives,No,Yes,Yes,WhatsApp,In real life (in person),NaN,2010,A few times per week,Find answers to specific questions,1-2 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Industry news about technologies you're interested in,29.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Neither easy nor difficult