In [3]:
import pandas as pd
df = pd.read_csv('./Data_2019/survey_results_public.csv')
schema_df = pd.read_csv('./Data_2019/survey_results_schema.csv')
pd.set_option('display.max_columns', 85) #to display all columns in the dataframe
pd.set_option('display.max_rows', 85)   #to see all rows in the dataframe of schema

In [4]:
people = {
    "first": ["Corey", "Jane", "John"],
    "last": ["Schafer", "Doe", "Smith"],
    "email": ["Corey.Schafer@gmail.com", "Jane.Doe@gmail.com", "John.Smith@gmail.com"]
}
df1 = pd.DataFrame(people)
df1

   first     last                    email
0  Corey  Schafer  Corey.Schafer@gmail.com
1   Jane      Doe       Jane.Doe@gmail.com
2   John    Smith     John.Smith@gmail.com

In [8]:
df1.columns[0:2]

Index(['first', 'last'], dtype='object')

In [12]:
df1['first']+df1['last']
#will add first and last name together 
# but there is no space in between.

0    CoreySchafer
1         JaneDoe
2       JohnSmith
dtype: object

In [11]:
# To add space we can do this
df1['first'] + ' ' + df1['last']

0    Corey Schafer
1         Jane Doe
2       John Smith
dtype: object

In [13]:
df1['full_name'] = df1['first'] + ' ' + df1['last']
df1

   first     last                    email      full_name
0  Corey  Schafer  Corey.Schafer@gmail.com  Corey Schafer
1   Jane      Doe       Jane.Doe@gmail.com       Jane Doe
2   John    Smith     John.Smith@gmail.com     John Smith

In [14]:
df1.drop(columns = ['first','last'],inplace=True)

In [15]:
df1

                     email      full_name
0  Corey.Schafer@gmail.com  Corey Schafer
1       Jane.Doe@gmail.com       Jane Doe
2     John.Smith@gmail.com     John Smith

In [16]:
df1['full_name'].str.split(' ',expand=True)

       0        1
0  Corey  Schafer
1   Jane      Doe
2   John    Smith

In [17]:
df1[['first','last']] = df1['full_name'].str.split(' ',expand=True)

In [18]:
df1

                     email      full_name  first     last
0  Corey.Schafer@gmail.com  Corey Schafer  Corey  Schafer
1       Jane.Doe@gmail.com       Jane Doe   Jane      Doe
2     John.Smith@gmail.com     John Smith   John    Smith

In [21]:
#df1.append({'first':'Tony'})
#gives error we need to specify ignore_index = True to avoid error.
df1.append({'first':'Tony'},ignore_index=True)

                     email      full_name  first     last
0  Corey.Schafer@gmail.com  Corey Schafer  Corey  Schafer
1       Jane.Doe@gmail.com       Jane Doe   Jane      Doe
2     John.Smith@gmail.com     John Smith   John    Smith
3                      NaN            NaN   Tony      NaN

In [22]:
people = {
    "first": ["Tony", "Steve"],
    "last": ["Stark", "Rogers"],
    "email": ["Ironman@avenge.com", "Cap@avenege.com"]
}
df2 = pd.DataFrame(people)

In [26]:
df1 = df1.append(df2,ignore_index=True)
df1

                     email      full_name  first     last
0  Corey.Schafer@gmail.com  Corey Schafer  Corey  Schafer
1       Jane.Doe@gmail.com       Jane Doe   Jane      Doe
2     John.Smith@gmail.com     John Smith   John    Smith
3       Ironman@avenge.com            NaN   Tony    Stark
4          Cap@avenege.com            NaN  Steve   Rogers
5       Ironman@avenge.com            NaN   Tony    Stark
6          Cap@avenege.com            NaN  Steve   Rogers

In [31]:
df1.drop(index =6,inplace=True)
df1

KeyError: '[6] not found in axis'

In [32]:
df1.drop(index =5,inplace=True)
df1

                     email      full_name  first     last
0  Corey.Schafer@gmail.com  Corey Schafer  Corey  Schafer
1       Jane.Doe@gmail.com       Jane Doe   Jane      Doe
2     John.Smith@gmail.com     John Smith   John    Smith
3       Ironman@avenge.com            NaN   Tony    Stark
4          Cap@avenege.com            NaN  Steve   Rogers

In [37]:
filt = df1['last'] == 'Rogers'
df1[filt]
df1 = df1.drop(index=df1[filt].index)

In [38]:
df1

                     email      full_name  first     last
0  Corey.Schafer@gmail.com  Corey Schafer  Corey  Schafer
1       Jane.Doe@gmail.com       Jane Doe   Jane      Doe
2     John.Smith@gmail.com     John Smith   John    Smith
3       Ironman@avenge.com            NaN   Tony    Stark